site_name: Notes
site_url: https://shubham-0819.github.io/notes
site_author: Shubham
site_description: Notes

# Repository
repo_name: shubham-0819/notes
repo_url: https://github.com/shubham-0819/notes

# Configuration
theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: white
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

  font:
    text: Nunito
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - blog
  - search:
      separator: '- \s\u200b\-_,:!=\- \]()"`/]+|\.(?!\d)|&- lg]t;|(?!\b)(?=- A-Z]- a-z])'

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/shubham-0819
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/Shubham_0819

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Page tree
nav:
  - Home: index.md
  # - Projects: projects/index.md
  - Concepts:
    - Overview: concepts/index.md
    - Operating Systems:
      - Overview: concepts/operating-systems/index.md
      - Storage in OS: concepts/operating-systems/overview-of-storage-in-an-operating-system.md
    - Data Structures: concepts/data-structure.md
    - Design Patterns: concepts/design-patterns.md
    - Programming:
      - Overview: concepts/programming/index.md
      - JavaScript: concepts/programming/javascript/index.md
      - Python: concepts/programming/python/index.md
      - Java: concepts/programming/java/index.md
  # - AI & ML:
  #   - Overview: ai/index.md
  #   - GenAI Models: ai/genai-models-by-openai.md
  #   - Best Practices: ai/best-practices-for-using-genai.md
  #   - Vector Embeddings: ai/vector-embedding.md
  - System Design:
    - Overview: system-design/index.md
    - Cloud & Infrastructure:
      - AWS Services: system-design/aws.md
    - Containers & Orchestration:
      - Docker: system-design/docker.md
      - Kubernetes: system-design/kubernetes.md
    - Message Queues:
      - RabbitMQ: system-design/rabbitmq.md
      - Kafka: system-design/kafka.md
    - Distributed Systems:
      - Overview: system-design/distributed/index.md
  - Databases:
    - Overview: databases/index.md
    - PostgreSQL: databases/postgreSQL-installation-and-basic-usage.md
    - NoSQL:
      - MongoDB: databases/mongodb.md
      - Redis: databases/redis.md
  - Development:
    - IDE & Tools:
      - Overview: ide/index.md
      - Essential Shell Tools: ide/essential-shell-tools.md
      - VSCode Extensions: ide/vscode-extensions.md
    - Frameworks:
      - Overview: frameworks/index.md
      - Frontend:
        - Angular: frameworks/angular.md
        - React: frameworks/frontend/react.md
      - Backend:
        - Node.js: frameworks/backend/nodejs.md
        - Spring Boot: frameworks/backend/spring-boot.md
      - Web Servers:
        - Apache: frameworks/apache.md
        - Nginx: frameworks/servers/nginx.md
  - Interview Prep:
    - Overview: interview/index.md
    - System Design: interview/system-design.md
    - JavaScript: interview/javascript-notes.md
    - Angular: interview/angular-notes.md
    - Java: concepts/programming/java/index.md
    - Database: interview/database.md
  - About Me: about.md
  

  # - Blog:
  #   - Overview: blog/index.md

