site_name: Notes
site_url: https://shubham-0819.github.io/notes
site_author: Shubham
site_description: Notes

# Repository
repo_name: shubham-0819/notes
repo_url: https://github.com/shubham-0819/notes

# Configuration
theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - blog
  - search:
      separator: '- \s\u200b\-_,:!=\- \]()"`/]+|\.(?!\d)|&- lg]t;|(?!\b)(?=- A-Z]- a-z])'

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/shubham-0819
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/Shubham_0819

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Docs:
    - how to use copilot: how-to-use-copilot.md
    - essential shell tools: ide/essential-shell-tools.md
    - vscode extensions: ide/vscode-extensions.md
    - apache: apache.md
    - overview of storage in an operating system: overview-of-storage-in-an-operating-system.md
    - PostgreSQL Installation and Basic Usage: postgreSQL-installation-and-basic-usage.md
    - GneAI models by OpenAI: genai-models-by-openai.md
    - Best Practices For Using GenAi : best-practices-for-using-genai.md
    - embeddings: vector-embeddings.md

